/**
 * Auto-update (M5, PLAN §6) — electron-updater against GitHub Releases.
 *
 * Behavior: check for updates at startup and periodically afterward, download in
 * the background, inform the renderer about the status, and apply on quit. The
 * feed comes from the `app-update.yml` generated by electron-builder
 * (publish: github, AdminCave/webaibuilder).
 *
 * Security stance (M0): the only renderer→main channel here (`update:restart`)
 * runs behind sender validation. No nodeIntegration, no additional attack
 * surface — the renderer only receives status pushes and may trigger exactly one
 * action (restart).
 *
 * Dev guard: `!app.isPackaged` → the real updater stays off (electron-updater
 * would have no `app-update.yml` in dev and would throw). The IPC handler is
 * registered anyway, so a "restart" call never runs into nothing.
 */

import { app, ipcMain } from 'electron';
import type { BrowserWindow } from 'electron';
import { autoUpdater } from 'electron-updater';
import type { ProgressInfo, UpdateInfo } from 'electron-updater';

import { DesktopIpcChannels, DesktopIpcEvents, type UpdateStatus } from '../shared/channels';
import { isTrustedIpcSender } from './security';

/** Check interval after startup (electron-updater downloads automatically). */
const CHECK_INTERVAL_MS = 6 * 60 * 60 * 1000; // 6 hours

let initialized = false;
let targetWindow: BrowserWindow | null = null;
/** Version of the found update — for progress/ready messages. */
let pendingVersion = '';

/** Push the current update status to the active window (if any). */
function pushStatus(status: UpdateStatus): void {
  const win = targetWindow;
  if (win !== null && !win.isDestroyed()) {
    win.webContents.send(DesktopIpcEvents.update, status);
  }
}

/** Registers the "restart now" action (always, even in dev = no-op). */
function registerRestartHandler(): void {
  ipcMain.handle(DesktopIpcChannels.updateRestart, (event) => {
    if (!isTrustedIpcSender(event)) {
      throw new Error(
        'IPC call on "update:restart" blocked from an untrusted sender.',
      );
    }
    if (!app.isPackaged) return; // Dev: no applicable update.
    // isSilent=false (installer visible on Windows), isForceRunAfter=true.
    autoUpdater.quitAndInstall(false, true);
  });
}

/** Wires the electron-updater events to status pushes. */
function wireAutoUpdaterEvents(): void {
  autoUpdater.on('checking-for-update', () => pushStatus({ phase: 'checking' }));

  autoUpdater.on('update-available', (info: UpdateInfo) => {
    pendingVersion = info.version;
    pushStatus({ phase: 'available', version: info.version });
  });

  autoUpdater.on('update-not-available', () => pushStatus({ phase: 'not-available' }));

  autoUpdater.on('download-progress', (progress: ProgressInfo) => {
    pushStatus({
      phase: 'downloading',
      version: pendingVersion,
      percent: Math.round(progress.percent),
    });
  });

  autoUpdater.on('update-downloaded', (info: UpdateInfo) => {
    pendingVersion = info.version;
    pushStatus({ phase: 'ready', version: info.version });
  });

  autoUpdater.on('error', (error: Error) => {
    pushStatus({ phase: 'error', message: error.message });
  });
}

/** Starts a check; errors land in the 'error' event (never unhandled). */
function checkNow(): void {
  autoUpdater.checkForUpdates().catch((error: unknown) => {
    const message = error instanceof Error ? error.message : String(error);
    pushStatus({ phase: 'error', message });
  });
}

/**
 * Initializes the updater and binds it to the (current) main window. Idempotent:
 * a repeated call (e.g. macOS `activate`) only updates the window reference;
 * listeners/handlers/interval are set up exactly once.
 */
export function initUpdater(win: BrowserWindow): void {
  targetWindow = win;
  if (initialized) return;
  initialized = true;

  registerRestartHandler();

  // Dev/unpackaged: no real update feed → only the no-op handler above.
  if (!app.isPackaged) return;

  autoUpdater.autoDownload = true; // download in the background
  autoUpdater.autoInstallOnAppQuit = true; // apply on quit

  wireAutoUpdaterEvents();

  checkNow();
  const timer = setInterval(checkNow, CHECK_INTERVAL_MS);
  // The interval should not keep the process alive.
  timer.unref?.();
}
